version: '3'

services:
  app:
    build: .
#      network_mode: host
    container_name: myjenkins
    volumes: 
      - ~/Documents/jenkins/jenkins_home:/var/jenkins_home
      - ~/Documents/jenkins/docker.sock:/var/run/docker.sock
    ports:
