version: '3'

services:
  grafana:
     links:
       - influxdb:influxdb
     image: grafana/grafana
     build: ./Grafana/
     container_name: grafana
     user: "104"
     ports:
       - "8857:3000"
     volumes:
       - ./Grafana/sources/grafana-home:/var/lib/grafana/
       - ./Grafana/sources/grafana-conf:/etc/grafana/
     restart: always 
  influxdb:
     image: influxdb
     build: ./InfluxDB/
     container_name: influxdb
     volumes:
       - ./InfluxDB/sources/data:/var/lib/influxdb/ 
       - ./InfluxDB/sources/config/:/etc/influxdb/ 
     ports:
        - "8086:8086"
     restart: always
  Jenkins:
    image: jenkins/jenkins
    build: ./Jenkins/
#      network_mode: host
    container_name: myjenkins
    ports:
       - "8181:8080"
       - "50000:50000"   
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock
      - ./Jenkins/sources/jenkins_home:/var/jenkins_home
#      - ./Jenkins/sources/docker-dind:/usr/local/bin/dind/
    restart: always
volumes:
    grafana-home:
    grafana-conf:
#    docker-dind:
    jenkins-home:
    influxdb:
